In [1]:
import numpy as np
from numpy import genfromtxt

In [3]:
data = genfromtxt('../DATA/bank_note_data.txt',delimiter=',')

In [7]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [8]:
data.shape

(1372, 5)

In [9]:
labels = data[:,4]

In [10]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [11]:
features = data[:,:4]

In [12]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [13]:
X,y = features,labels

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
X_train.shape

(1097, 4)

In [18]:
X_test.shape

(275, 4)

In [19]:
from sklearn.preprocessing import MinMaxScaler

In [20]:
scaler_object = MinMaxScaler()

In [21]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [24]:
scale_X_train = scaler_object.transform(X_train)

In [25]:
scale_X_test = scaler_object.transform(X_test)

In [27]:
from keras.models import Sequential
from keras.layers import Dense

In [31]:
model = Sequential()
model.add(Dense(4,input_dim=4,activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [32]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [33]:
model.fit(scale_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
 - 1s - loss: 0.6675 - acc: 0.5597
Epoch 2/50
 - 0s - loss: 0.6612 - acc: 0.5597
Epoch 3/50
 - 0s - loss: 0.6529 - acc: 0.5597
Epoch 4/50
 - 0s - loss: 0.6397 - acc: 0.5597
Epoch 5/50
 - 0s - loss: 0.6222 - acc: 0.5597
Epoch 6/50
 - 0s - loss: 0.6035 - acc: 0.5624
Epoch 7/50
 - 0s - loss: 0.5853 - acc: 0.5634
Epoch 8/50
 - 0s - loss: 0.5666 - acc: 0.5907
Epoch 9/50
 - 0s - loss: 0.5456 - acc: 0.6855
Epoch 10/50
 - 0s - loss: 0.5215 - acc: 0.7648
Epoch 11/50
 - 0s - loss: 0.4979 - acc: 0.7958
Epoch 12/50
 - 0s - loss: 0.4745 - acc: 0.8277
Epoch 13/50
 - 0s - loss: 0.4525 - acc: 0.8423
Epoch 14/50
 - 0s - loss: 0.4315 - acc: 0.8678
Epoch 15/50
 - 0s - loss: 0.4111 - acc: 0.8678
Epoch 16/50
 - 0s - loss: 0.3914 - acc: 0.8979
Epoch 17/50
 - 0s - loss: 0.3728 - acc: 0.8915
Epoch 18/50
 - 0s - loss: 0.3544 - acc: 0.9034
Epoch 19/50
 - 0s - loss: 0.3372 - acc: 0.9216
Epoch 20/50
 - 0s - loss: 0.3212 - acc: 0.9170
Epoch 21/50
 - 0s - loss: 0.3048 - acc: 0.9289
Epoch 22/50
 - 0s - lo

In [38]:
model.predict_classes(scale_X_test)

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    

In [39]:
model.metrics_names

['loss', 'acc']

In [40]:
from sklearn.metrics import confusion_matrix,classification_report

In [41]:
preds = model.predict_classes(scale_X_test)

In [42]:
confusion_matrix(y_test,preds)

array([[144,   4],
       [  9, 118]], dtype=int64)

In [44]:
print(classification_report(y_test,preds))

             precision    recall  f1-score   support

        0.0       0.94      0.97      0.96       148
        1.0       0.97      0.93      0.95       127

avg / total       0.95      0.95      0.95       275



In [45]:
model.save('mymodel.h5')

In [46]:
from keras.models import load_model

In [47]:
newmodel = load_model('mymodel.h5')

In [49]:
newmodel.predict_classes(scale_X_test)

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    